<?
$title = 'ATS 24 | Supplier Terms & Conditions';
$meta_descr = 'Advanced Technology Supply, Inc supplier terms and conditions for products and services';
include 'inc_header.php'; ?>



	<section class="section-intro pb0">

		<div class="container">

			<div class="row mb30">

				<div class="col-12">

					<h1 class=" mb20">AS9100 Supplier Terms and Conditions </h1>

					<p class="mb30"><b>GENERAL:</b> As a supplier to Advanced Technology Supply, Inc. (ATS), you become a key contributor to the products and services that we deliver to our customers.  We value the conformance of your products and services with our contribution to product safety and ethical business practices to cast our customers’ requirements and satisfaction. As a Supplier (Seller) to ATS (Buyer), the Seller agrees to meet the following stipulations for AS9100 requirements for the purchase order or subcontract, hereafter referred to as the “Order”.  These terms and conditions apply to all external suppliers and vendors which furnish products, processes, and/or services.</p>

					<p class="mb30"><b>Definitions:</b> For the purpose of this document, the terms and definitions given in ISO 9000:201 and AS9100 shall apply.</p>

					<ol>
					<li><b>Final Approval</b> &mdash; Buyer reserves the right of final approval of product, procedures, processes, and equipment as well as the release of product and services.</li>
					<li><b>Approved Quality Management System (QMS)</b> &mdash; Supplier is expected to implement and maintain a Quality Management System.  Buyer reserves the right to review and approve Seller Quality Management System for Seller’s use in supplying supplies or services to the Buyer. Maintenance organizations shall be required to have any required QMS approvals and other approvals, certificates, ratings, licenses, and permits required by applicable statutory and regulatory requirements.</li>
					<li><b>Design and Development Control Including Critical Items and Key Characteristics</b> &mdash; The Seller shall maintain the proper identification and revision status of specifications, drawings, process requirements, inspection/verification instructions and other relevant technical data used in the performance of requirements of this Order. The Seller shall use technical data at the contractually specified revision or at the latest revision in effect at the time of contract award, if not specified.</li>
					<li><b>Certified Personnel & Certifying Staff</b> &mdash; The Seller shall ensure that all personnel are properly qualified to perform the work required to support the Order, including having the proper certification to perform special processes, tasks and maintenance required by the purchase requirement. The Buyer reserves the right to review all documentation supporting qualification of Seller or Seller’s sub-tier personnel and Certifying Staff.</li>
					<li><b>Buyer Approvals</b> &mdash; Buyer reserves the right to approve or specify any products, services, designs, methods, processes, utilization of equipment, tests, inspection plans, verifications, use of statistical techniques for product acceptance, the release of products and services, and any applicable critical items, including key characteristics.</li>
					<li><b>Test Inspection and Verification Requirements</b> &mdash; Buyer reserves the right to designate requirements for test specimens for design approval, inspection and verification, investigation or auditing.  This includes a provision of test specimens which appropriate documentation as to the production method, number and storage conditions when requested</li>
					<li><b>Records Retention</b> &mdash; The Seller is required to retain all records related to this Order, including objective evidence of the quality of any items supplied (manufacturing, assembly, inspection, physical/chemical test reports, test and special process records and material certification records) for a period of seven (7) years after the final payment. Records shall be made available to Buyer upon request and at no additional charge.  Documents to be dispose up in accordance with acceptable methods as approved by ATS in the Seller’s QMS.</li>
					<li><b>Calibration</b> &mdash; All Sellers providing calibration services shall be required to be compliant to ANSI Z540 (or equivalent). All calibration certificates shall identify standards used and shall be traceable to NIST (National Institute of Standards Technology).</li>
					<li><b>Approved Processors and External Providers</b> &mdash; Where required on the Order, Seller shall utilize only Buyer/Customer-approved special process sources.</li>
					<li><b>Nonconforming Product/Material</b> &mdash; The Seller shall maintain a documented procedure for control of nonconforming product. The Seller shall notify the Buyer in the event of nonconforming product/material to include post-delivery within 24 hours of discovery. Only the Buyer’s authorized Quality and Project Managers may disposition acceptance or rejection of the Seller’s Nonconforming product/material, as coordinated thru the Buyer’s Contract Representative.</li>
					<li><b>Changes Notification Requirement</b> &mdash; The Seller shall notify the Buyer of any changes to a product’s design, development, processes, manufacturers/suppliers, manufacturing location, and/or quality management system approval status. Seller shall obtain written approval from the Buyer’s Contract Representative (all as coordinated with and authorized by the Buyer’s Technical Representative) before delivering product affected by any such changes.</li>
					<li><b>Right of Entry/Access</b> &mdash; Buyer, its customers and regulatory authorities reserve the right of access to all supplier facilities, at any level of the supply chain, performing work on the Order and to all applicable records. The Seller is required to provide support in the form of labor, materials, information, tools and equipment necessary to execute verification and survey activities.</li>
					<li><b>Flow Down Requirement</b> &mdash; The Seller shall flow down all applicable Buyer, Customer, U.S. Government (hereafter referred to as Customer), Regulatory and/or AS9100 requirements to sub-tier suppliers (including requirements in the purchasing documents and key characteristics where require<b>d)</b>. However, Buyer does not allow Seller to subcontract any product or process to a sub-tier supplier without prior expressed written consent of the Buyer, through the Buyer’s Contract Representative.</li>
					<li><b>Verification of Purchased Product</b> &mdash; The Seller is responsible for conformity of all products purchased from suppliers/processors, including from sources defined by the Buyer or Buyer’s Customer. Unless specifically authorized by the Buyer, Seller is not authorized to release purchased product for use until completion of all required verification activities. If approved by Buyer, Sellers documented procedures must include provisions for identification and records to allow recall and replacement if it is subsequently found that the product does not meet requirements.</li>
					<li><b>Delegated Inspection Authority and Approval of Statistical Techniques</b> &mdash; When appropriate, the Buyer may delegate the inspection authority to the Seller, if the Seller has capability and approval to conduct such inspections. The Buyer will define the inspection requirements (including approved monitoring and measurement equipment/methods as well as any statistical techniques employed for product acceptance) in the Order and the Buyer will maintain a record of approval granted to Seller to carry out such inspections. The Seller shall maintain a record of the delegation approval and present it with the product at delivery. Delegation of any inspection authority does not absolve the Seller of performing all appropriate inspections prior to shipment, or of its responsibility to provide conforming product, nor will it preclude subsequent rejection by the Buyer.</li>
					<li><b>Source Inspection/Verification</b> &mdash; The Buyer also may perform inspection activities at the point of origin (Seller’s or its sub-tier’s facilities) to ensure that purchased product meets purchase requirements prior to shipment/delivery to the Buyer. When the Buyer intends to perform verification at the point of origin, the Buyer will define the intended verification arrangements and the method of product release in the solicitation and in the Order. The Seller shall provide support to include, but not limited to labor, materials, tools and equipment necessary to perform the needed verification activities and shall provide access to the Buyer to all facilities where work is performed for the Order. The Seller is responsible for conformity of all products purchased from suppliers/processors, including from sources defined by the Buyer or Buyer’s Customer. Verification and/or acceptance by the Buyer shall not be utilized by the Seller as evidence of effective control of quality by the Seller and shall not absolve the Seller of the responsibility to provide conforming product, nor will it preclude subsequent rejection by the Buyer.</li>
					<li><b>Customer/Government Source Inspection/Verification</b> &mdash; The Buyer’s Customer/Government (also referred to as “Customer”) may perform inspection activities at the point of origin (Seller’s or its sub-tier’s facilities) to ensure that purchased product meets purchase requirements prior to shipment/delivery to the Buyer/Customer. When the Buyer’s Customer intends to perform verification at the point of origin, the Buyer will define the intended verification arrangements and the method of product release in the solicitation and in the Order. The Seller shall provide support to include, but not limited to labor, materials, tools and equipment necessary to perform the needed verification activities and shall provide access to the Buyer and Buyer’s Customer to all facilities where work is performed for the Order. The Seller is responsible for conformity of all products purchased from suppliers/processors, including from sources defined by the Buyer or Buyer’s Customer. Verification and/or acceptance by the Buyer’s Customer shall not be utilized by Buyer or Seller as evidence of effective control of quality by the Seller and shall not absolve the Buyer or the Seller of the responsibility to provide conforming product, nor shall it preclude subsequent rejection by the Buyer or Buyer’s Customer.</li>
					<li><b>Counterfeit and Suspected Unapproved Parts</b> &mdash; To prevent the purchase of counterfeit or suspect/unapproved products and to ensure product identification and traceability (and for other reasons), the Buyer implements controls that include the requirement of material verification and traceability to include, but not limited to Material Certificates, Certificates of Conformity, special tests and inspections and/or other supporting documentation from the Seller as is appropriate, as specified in the Order. The Seller agrees to use commercially reasonable practices to prevent counterfeit work from being delivered to the Buyer. The Seller shall only purchase new and authentic materials to be used in products to be delivered to the Buyer directly from the Original Component Manufacturer (OCM) or Original Equipment Manufacturer (OEM). Product shall not be acquired from distributors or brokers unless approved in advance in writing by the Buyer through the Buyer’s Contract Representative.</li>
					<li><b>Corrective Action Request</b> &mdash; Where product or process non-conformances are identified by the Buyer or its Customer, a Corrective Action Request (CAR) may be issued to the Seller. The Seller agrees to take appropriate and timely action to respond to the CAR with an acceptable corrective action plan, subject to Buyer approval, and to implement the required corrective actions. When the Seller does not provide a timely and/or effective corrective action plan, the Buyer will take appropriate measures such as, but not limited to, termination for default, withholding payment, removing Supplier from the Buyer’s Approval Supplier List, and/or legal action, as appropriate and solely at the Buyer’s discretion.</li>
					<li><b>Supplier Approval</b> &mdash; The Seller is responsible for maintaining a Supplier Register with documentation to support their selection of subcontractors based on their ability to supply product that fulfill the Buyer’s Order, including, but not limited to, evidence of customer-approved processor status. The Seller is responsible for assuring their subcontractors holds the required approvals and certificates to provide the purchased product and for applying the appropriate level of control over the subcontractor’s performance to assure compliance with the Order. However, the Buyer does not permit the Seller to subcontract any portion of the Order without prior written approval from the Buyer’s Contract Representative.</li>
					<li><b>Purchasing Information and Flow Down Requirements</b> &mdash; The Seller shall maintain purchasing records and ensure flow-down requirements are in place for all procurement actions related to the Buyer’s Order that includes purchase orders that fully describe the product to be purchased, including, where appropriate, requirements for: <b>a)</b> approval of product, procedures, processes, and equipment, <b>b)</b> qualification of personnel, <b>c)</b> quality management system, <b>d)</b> identification and revision status of all technical documents, <b>e)</b> design, test, inspection, verification (including maintenance process verification), use of statistical techniques for product acceptance, and related instructions for acceptance, and as applicable critical items including key characteristics, <b>f)</b> test specimens for design approval, inspection/verification, investigation or auditing, <b>g)</b> regarding non-conforming product notification and disposition approvals, and notification of changes in product process, suppliers, manufacturing facility locations and for obtaining approvals thereof, and flow down of requirements to the sub-tiers, <b>h)</b> records retention, <b>i)</b> right of access, <b>j)</b> specific authority approval, <b>k)</b> format and content of the delivery documentation package, and <b>l)</b> conditions under which product malfunctions, defects and un-airworthy conditions have to be reported to the Buyer and appropriate concerned Stakeholders (Reference AS9110 8.4.3).</li>
					<li><b>Production and Service Provisions</b> &mdash; The Seller shall control production and services by planning and carrying out production and services under controlled conditions, taking into consideration, as appropriate, processes controls to manage critical items, variable data as it applies to design, manufacturing and tooling, identification of in-process inspection/verification points when conformance cannot be verified at later stages of realization, and performance of special processes. Controlled conditions shall include, as applicable: <b>a)</b> information that describes the characteristics of the product, <b>b)</b> work instructions, <b>c)</b> suitable equipment such as jigs, fixtures, molds and software programs, <b>d)</b> monitoring and measuring equipment traceable to NIST, <b>e)</b> implementation of monitoring and measurement, <b>f)</b> implementation of product release, delivery, and post-delivery activities, <b>g)</b> accountability of all product during maintenance such as parts quantities, split orders and nonconforming product, <b>h)</b> evidence of completion of all inspection/verification as planned/required, <b>i)</b> provisions for prevention, detection and removal of foreign objects (including tools), <b>j)</b> monitoring and controlling utilities and supplies to the extent they affect conformity to product requirements (e.g.; water, compressed air, electricity, chemical products), <b>k)</b> clear workmanship criteria, <b>l)</b> compliance with standards, quality plans, manufacturers’ recommendations, customer specifications and or documented procedures, <b>m)</b> maintaining a list of approved maintenance process capabilities and/or ratings, <b>n)</b> assuring that maintenance operations does not adversely affect areas outside the scope of the planned maintenance; and <b>o)</b> utilization of equipment, tools and materials recommended in the technical data for the article or as equivalent as approved by the authority.</li>
					<li><b>Validation of Special Processes</b> &mdash; The Seller shall validate any process for production and service provision where the resulting output cannot be verified by subsequent monitoring or measurement (Special Processes) to assure compliance with the requirements of the applicable technical data issued by the design approval holder. Validation shall demonstrate the ability of these processes to achieve planned results. The Seller shall establish arrangements for these processes including, as applicable: <b>a)</b> defined criteria for review and approval of the processes, <b>b)</b> approval of equipment and qualifications of personnel, <b>c)</b> use of specific methods and procedures, <b>d)</b> requirements for records, and <b>e)</b> revalidation.</li>
					<li><b>Traceability</b> &mdash; To ensure product identification and traceability, ATS will institute controls that include the requirement of material certificates, Certificates of Conformity, and/or other supporting documentation from its suppliers as is appropriate.  Accordingly, documented information such as Test Reports, Material Certs., and/or Certificates of Conformity shall accompany all orders.</li>
					<li><b>Timeliness of Delivery</b> &mdash; The supplier shall immediately notify ATS and explain any circumstances, which may delay the timely performance of the purchase order and shall continue to notify ATS of any significant changes in delivery status</li>
					<li><b>Monitoring and Measurement of Product</b> &mdash; The Seller shall monitor and measure the characteristics of product, at appropriate stages, to verify that product requirements have been met. Objective evidence of conformity of the acceptance criteria shall be maintained.</li>
					<li><b>Personnel Contribution</b> &mdash; The Seller must ensure that their personnel are aware of their contributions to product conformity and product safety as well as the importance of ethical behavior.</li>
					</ol>

					<p class="mb30">ATS’s suppliers are a critical part of our success. To supply top quality products and services responsibly, we understand and expect our suppliers will have an internal code of ethics and business conduct, best practices for enhancing product safety, and will maintain compliance with all laws and regulations applicable to your operation of business.  If you have any questions regarding these specifications and requirements, assistance is available. Contact ATS at <a href="tel:+18007936307">800-793-6307</a>.</p>

				</div>

			</div>

		</div>

	</section>


<style>
li { margin-bottom: 2rem; }
</style>

<? include 'inc_footer.php'; ?>
